# Build Stage 1

FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

# Copy package.json and your lockfile, here we add pnpm-lock.yaml for illustration
COPY package.json ./

# Install dependencies
RUN npm install --only=production

# Copy the entire project
COPY . ./

# Build the project
RUN npm run build

# Build Stage 2

FROM node:22-alpine
WORKDIR /app

# Only `.output` folder is needed from the build stage
COPY --from=build /app/.output/ ./

# Change the port and host
ENV PORT 3000
ENV HOST 0.0.0.0
ENV DATABASE_URL="file:./dev.db"
ENV PAYSTACK_SECRET_KEY="pk_test_eb3bc9ba87ba3fe7f19a2fe09d4a7132ea9d37b2"
ENV JWT_SECRET="4f385fa75a046837ae04343a4c691340ee98a0916d68e956ab91a4812e9619bb"


EXPOSE 3000/tcp

CMD ["node", "/app/server/index.mjs"]
